spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    mongodb:
      uri: ${MONGO_URI}

  datasource:
    url: ${LOCAL_DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_HOST}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        show_sql: true

    database: mysql

    database-platform: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.springframework.security: debug

kafka:
  url: ${KAFKA_URL}

custom:
  domain:
    image:
      baseUrl: ${BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics, tempo

server:
  port: 8504