name: Java CI with Gradle V0.1

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up admin-api application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./admin-api/src/main/resources/application.yml
        env:
          jasypt.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Set up alert-api application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./alert-api/src/main/resources/application-prod.yml
        env:
          jasypt.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Set up chatting-api application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./chatting-api/src/main/resources/application.yml
        env:
          jasypt.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Set up domain-mongodb test application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./domain-mongodb/src/test/resources/application.yml
        env:
          jasypt.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Test domain-mysql with Gradle
        run: |
          cd domain-mysql
          chmod +x ./gradlew
          ./gradlew clean test

      - name: Test domain-mongodb with Gradle
        run: |
          cd domain-mongodb
          chmod +x ./gradlew
          ./gradlew clean test

      - name: Build admin-api with Gradle
        run: |
          cd admin-api
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Build alert-api with Gradle
        run: |
          cd alert-api
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Build chatting-api with Gradle
        run: |
          cd chatting-api
          chmod +x ./gradlew
          ./gradlew clean build
